#!/bin/bash
#SBATCH --job-name PolyAla
#SBATCH --nodes 1
#SBATCH --cpus-per-task 1
#SBATCH --tasks-per-node 1
#SBATCH --mem 4096
#SBATCH -t 48:00:00


module load gromacs-plumed/openmpi/intel/2016.4

# Prep inputs and run NVT equilibration on node
gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr
gmx mdrun -deffnm nvt

# Prep inputs and run NPT equilibration on node
gmx grompp -f npt.mdp -c nvt.gro -r nvt.gro -t nvt.cpt -p topol.top -o npt.tpr
gmx mdrun -deffnm npt

